import type { Metadata } from "next";
import type { ReactNode } from "react";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import {UserProvider} from "../lib/Authcontext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (   
    <html lang="en">
      <body className="min-h-screen bg-white text-black">
        <UserProvider>
          <Header />
          <div className="flex h-[calc(100vh-48px)]">
            <Sidebar />
            <main className="flex-1 p-4">{children}</main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
